language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

addons:
  chrome: stable

before_script:
  - npm install -g @angular/cli

script:
  - cd dagger-app
  - npm install
  - npm install --save-dev @angular-devkit/build-angular
  - ng build --prod
  - ng test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $sh72hiw82hela823hrkjn29
  local_dir: dist
  on:
    branch: master
