language: node_js
node_js:
  - "10"

dist: trusty
sudo: false

addons:
  chrome: stable

before_script:
  - npm install -g @angular/cli

script:
  - cd dagger-app
  - npm install --save-dev @angular-devkit/build-angular
  - ng build --prod --aot --base-href /dagger/
#  - ng test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $sh72hiw82hela823hrkjn29
  local_dir: dagger-app/dist/dagger-app
  on:
    branch: master
