language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm run lint
  - npm run test:headless
  - npm run build
  - xvfb-run npm run e2e

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $sh72hiw82hela823hrkjn29
  local_dir: dist
  on:
    branch: master