language: node_js
node_js:
  - "10"
dist: trusty
sudo: required

addons:
  chrome: stable

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
  - npm install -g @angular/cli

script:
  - cd dagger-app
#  - npm install
#  - npm install --save-dev @angular-devkit/build-angular
  - ng build --prod --aot
  - ng test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $sh72hiw82hela823hrkjn29
  local_dir: dist
  on:
    branch: master
